<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_Integer" KindOfPOU="Element">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Integer
VAR_INPUT
    nInput  : INT;
END_VAR
VAR_OUTPUT
    nResult : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[nResult := nInput + 1;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
