<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_Real" KindOfPOU="Element">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Real
VAR_INPUT
    rInput : REAL;
END_VAR
VAR_OUTPUT
    rResult : REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[rResult := rInput * 2.0;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
