<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="FB_String" KindOfPOU="Element">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_String
VAR_INPUT
    sInput : STRING;
END_VAR
VAR_OUTPUT
    sOutput : STRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[sOutput := CONCAT('Value: ', sInput);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
